/* Mapping from SF Symbols (used throughout SwiftUI code) to Phosphor icons.
   Phosphor was picked because its `bold` weight matches SF Symbols'
   default semibold rendering, and its `fill` weight is the direct
   equivalent of iOS `.fill` symbol variants — the visual DNA is much
   closer than what Lucide gives us. Populated as we port screens;
   unknown names fall back to <Question /> so gaps fail visibly. */
import {
  Airplane,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowsLeftRight,
  ArrowUp,
  Bell,
  Book,
  BookOpen,
  Books,
  Brain,
  Briefcase,
  CaretDown,
  CaretRight,
  ChartBar,
  ChatCircleDots,
  ChatsCircle,
  Check,
  Circle,
  Confetti,
  FileText,
  Flame,
  Folder,
  ForkKnife,
  Gear,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Hourglass,
  House,
  Image as ImageIcon,
  CheckCircle,
  Clock,
  FilePlus,
  Flag,
  Lightning,
  Lightbulb,
  ListBullets,
  ListChecks,
  MagicWand,
  Microphone,
  Minus,
  NotePencil,
  Play,
  Pencil,
  PencilLine,
  PersonSimpleWalk,
  Plus,
  Question,
  Quotes,
  Rabbit,
  SealCheck,
  Sparkle,
  SquaresFour,
  Stack,
  Star,
  Target,
  TextAa,
  TextAlignLeft,
  TextHOne,
  Translate,
  Trash,
  Tray,
  WarningCircle,
  XCircle,
  User,
  UserCircle,
  Warning,
  Waveform,
  X,
  type Icon as PhosphorIcon,
} from '@phosphor-icons/react';

/* SF-Symbol name (as written in Swift source) → Phosphor component.
   Both outlined and .fill variants map to the same component — the Icon
   wrapper reads the trailing `.fill` off the name to pick the weight. */
const SF_TO_PHOSPHOR: Record<string, PhosphorIcon> = {
  house: House,
  'house.fill': House,
  folder: Folder,
  'folder.fill': Folder,
  plus: Plus,
  'square.stack.3d.up': Stack,
  'square.stack.3d.up.fill': Stack,
  person: User,
  'person.fill': User,
  'person.crop.circle.fill': UserCircle,
  'bubble.left.and.bubble.right': ChatsCircle,
  headphones: Headphones,
  book: BookOpen,
  'book.closed': BookOpen,
  'pencil.and.scribble': PencilLine,
  'chart.bar.fill': ChartBar,
  target: Target,
  'flame.fill': Flame,
  bell: Bell,
  circle: Circle,
  'arrow.left': ArrowLeft,
  'arrow.right': ArrowRight,
  'chevron.right': CaretRight,
  'chevron.down': CaretDown,
  xmark: X,
  sparkles: Sparkle,
  sparkle: Sparkle,
  checkmark: Check,
  pencil: Pencil,
  waveform: Waveform,
  mic: Microphone,
  'mic.fill': Microphone,
  photo: ImageIcon,
  'doc.text.fill': FileText,
  /* Stub flashcard-set icons (Phase 2 demo data; real icons come from
     set.icon in Phase 3). */
  airplane: Airplane,
  'fork.knife': ForkKnife,
  'briefcase.fill': Briefcase,
  /* Create-set preview icons + suggester outputs. */
  'rectangle.stack.fill': Stack,
  'book.closed.fill': BookOpen,
  'book.fill': BookOpen,
  'text.book.closed.fill': BookOpen,
  'graduationcap.fill': GraduationCap,
  'brain.head.profile': Brain,
  'globe.europe.africa.fill': Globe,
  'star.fill': Star,
  'heart.fill': Heart,
  'bolt.fill': Lightning,
  'pencil.and.outline': Pencil,
  'character.bubble.fill': Translate,
  /* Phase 4 Writing */
  'square.grid.2x2.fill': SquaresFour,
  'note.text.badge.plus': NotePencil,
  'book.pages.fill': Book,
  lightbulb: Lightbulb,
  'lightbulb.fill': Lightbulb,
  'arrow.right.circle.fill': ArrowRight,
  'arrow.uturn.backward': ArrowLeft,
  /* Phase 4C3 helper toolbar */
  'character.book.closed.fill': Translate,
  'textformat.abc.dottedunderline': TextAa,
  /* Phase 4B WriteWords difficulty + result */
  'hare.fill': Rabbit,
  'figure.walk': PersonSimpleWalk,
  'party.popper.fill': Confetti,
  hourglass: Hourglass,
  gearshape: Gear,
  'gearshape.fill': Gear,
  /* Phase 4D GrammarNotes — note types + block types + editor */
  'arrow.left.arrow.right': ArrowsLeftRight,
  'checklist.checked': ListChecks,
  checklist: ListChecks,
  'text.alignleft': TextAlignLeft,
  'textformat.size.larger': TextHOne,
  'textformat.size': TextHOne,
  'list.bullet': ListBullets,
  'quote.opening': Quotes,
  minus: Minus,
  'arrow.up': ArrowUp,
  'arrow.down': ArrowDown,
  trash: Trash,
  'exclamationmark.triangle.fill': Warning,
  /* Phase 4D2 grammar quiz */
  'pencil.line': PencilLine,
  'square.and.pencil': NotePencil,
  'wand.and.stars': MagicWand,
  'checkmark.circle': CheckCircle,
  'checkmark.circle.fill': CheckCircle,
  'questionmark.circle.fill': Question,
  'play.fill': Play,
  /* Phase 4D3 spaced review */
  'xmark.circle.fill': XCircle,
  'checkmark.seal.fill': SealCheck,
  'tray.fill': Tray,
  /* Phase 4D4 templates */
  'clock.fill': Clock,
  'flag.fill': Flag,
  'doc.badge.plus': FilePlus,
  /* Phase 4D5 quick mistake */
  'exclamationmark.bubble.fill': ChatCircleDots,
  'exclamationmark.circle.fill': WarningCircle,
  /* Phase 5 Reading */
  'books.vertical.fill': Books,
};

export const iconForSFSymbol = (name: string): PhosphorIcon =>
  SF_TO_PHOSPHOR[name] ?? Question;

export type SFSymbolWeight = 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';

/* SF Symbols with a `.fill` suffix render as solid on iOS. Everything else
   we render `bold`, which is the closest match to SwiftUI's default
   `.semibold` rendering under `.font(.system(size:weight:))`. */
export const weightForSFSymbol = (name: string): SFSymbolWeight =>
  name.endsWith('.fill') ? 'fill' : 'bold';
